### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by happyday22** [ucrparlay/Parallel-SSSP#1]
Hello, we use g++ 5.4.0 to compile, but there are the following errors. 
![3](https://user-images.githubusercontent.com/30362615/174727561-8a3d3d3d-1673-4cba-b499-af1240285836.PNG)

**Comment by happyday22** [comment]
Also, could you please provide an example of the input graph

**Comment by Akatsukis** [comment]
Hi there,

Thank you for pointing it out! ;) I just realized gcc-5 does not have complete support for all C++17 features we used. I already updated the README. Could you try again with gcc-7? FYI, we did the experiment with g++ 7.5.0.

Regarding an example input graph, I uploaded a graph to [Google drive](https://drive.google.com/drive/u/3/folders/1ZuhfaLmdL-EyOiWYqZGD1rOy_oSFRWe4). It's a directed graph from [SNAP](http://snap.stanford.edu/data/soc-LiveJournal1.html) with synthetic edge weights.

Let me know if you have further questions.
